In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score, recall_score, accuracy_score

In [2]:
dataset = pd.read_csv("iris.csv")
X = dataset.iloc[:,:4].values
y = dataset['Species'].values
dataset.head(5)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [3]:
X_train,X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

In [4]:
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [5]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [6]:
y_pred = classifier.predict(X_test)

In [7]:
from sklearn.metrics import confusion_matrix 
cm = confusion_matrix(y_test, y_pred) 
from sklearn.metrics import accuracy_score
print("Accuracy : ", accuracy_score(y_test, y_pred))
print(cm)

Accuracy :  1.0
[[ 9  0  0]
 [ 0 10  0]
 [ 0  0 11]]

In [8]:
df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})
df

        Real Values Predicted Values
0    Iris-virginica   Iris-virginica
1       Iris-setosa      Iris-setosa
2    Iris-virginica   Iris-virginica
3       Iris-setosa      Iris-setosa
4   Iris-versicolor  Iris-versicolor
5   Iris-versicolor  Iris-versicolor
6    Iris-virginica   Iris-virginica
7   Iris-versicolor  Iris-versicolor
8       Iris-setosa      Iris-setosa
9       Iris-setosa      Iris-setosa
10  Iris-versicolor  Iris-versicolor
11  Iris-versicolor  Iris-versicolor
12   Iris-virginica   Iris-virginica
13   Iris-virginica   Iris-virginica
14   Iris-virginica   Iris-virginica
15  Iris-versicolor  Iris-versicolor
16      Iris-setosa      Iris-setosa
17      Iris-setosa      Iris-setosa
18      Iris-setosa      Iris-setosa
19   Iris-virginica   Iris-virginica
20   Iris-virginica   Iris-virginica
21      Iris-setosa      Iris-setosa
22   Iris-virginica   Iris-virginica
23  Iris-versicolor  Iris-versicolor
24   Iris-virginica   Iris-virginica
25  Iris-versicolor  Iris-versicolor
26   Iris-virginica   Iris-virginica
27  Iris-versicolor  Iris-versicolor
28  Iris-versicolor  Iris-versicolor
29      Iris-setosa      Iris-setosa

In [9]:
m = accuracy_score(y_test, y_pred)
print("Error Rate: ", 1-m)
print("Precision : ", precision_score(y_test, y_pred, average = "micro"))
print("Recall score: ", recall_score(y_test, y_pred, average="micro"))

Error Rate:  0.0
Precision :  1.0
Recall score:  1.0