In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("iris.csv")
df1 = pd.read_csv("StudentPerformance.csv")

In [4]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [5]:
df1.describe()

,Roll_no,math_score,Reading_score,Writing_score,Placement_score,Club_Join_Date
count,80.0000,77.000000,76.000000,77.000000,77.000000,76.000000
mean,40.5000,73.493506,82.657895,70.493506,87.779221,2021.052632
std,23.2379,20.111939,4.779268,6.025436,7.903403,1.979190
min,1.0000,60.000000,75.000000,60.000000,75.000000,2018.000000
25%,20.7500,66.000000,79.000000,66.000000,82.000000,2019.000000
50%,40.5000,71.000000,82.000000,70.000000,86.000000,2021.000000
75%,60.2500,75.000000,87.000000,76.000000,95.000000,2023.000000
max,80.0000,219.000000,90.000000,80.000000,105.000000,2024.000000

In [6]:
df1.groupby(df1.Club_Join_Date).count()

,Roll_no,Name,div,math_score,Reading_score,Writing_score,Placement_score
Club_Join_Date,,,,,,,
2018.0,9,9,9,9,7,9,8
2019.0,12,12,12,10,12,11,12
2020.0,11,11,11,11,11,11,9
2021.0,11,11,11,10,11,10,11
2022.0,11,11,11,11,11,10,11
2023.0,11,11,11,11,9,11,11
2024.0,11,11,11,11,11,11,11

In [7]:
df1.groupby(df1.Club_Join_Date).min()

,Roll_no,Name,div,math_score,Reading_score,Writing_score,Placement_score
Club_Join_Date,,,,,,,
2018.0,6,Rutuja,A,63.0,77.0,64.0,78.0
2019.0,2,anita,A,60.0,76.0,64.0,75.0
2020.0,14,ajay,A,62.0,76.0,61.0,83.0
2021.0,3,gauri,A,61.0,75.0,62.0,78.0
2022.0,16,chaya,A,65.0,75.0,60.0,75.0
2023.0,13,akansha,A,61.0,75.0,60.0,77.0
2024.0,1,aman,A,64.0,75.0,60.0,76.0

In [8]:
df1.groupby(df1.Club_Join_Date).max()

,Roll_no,Name,div,math_score,Reading_score,Writing_score,Placement_score
Club_Join_Date,,,,,,,
2018.0,79,vijay,B,78.0,88.0,80.0,100.0
2019.0,68,varun,B,219.0,90.0,79.0,97.0
2020.0,73,tejas,B,78.0,90.0,80.0,105.0
2021.0,72,yash,B,154.0,90.0,80.0,100.0
2022.0,80,vedika,B,79.0,90.0,78.0,99.0
2023.0,75,tejal,B,79.0,88.0,78.0,99.0
2024.0,78,vijay,B,80.0,90.0,80.0,98.0

In [9]:
df1['Placement_score']=pd.to_numeric(df1['Placement_score'],errors='coerce')

In [10]:
df1.groupby(df1.Club_Join_Date).mean(numeric_only=True)

,Roll_no,math_score,Reading_score,Writing_score,Placement_score
Club_Join_Date,,,,,
2018.0,41.111111,70.888889,81.000000,71.777778,88.750000
2019.0,28.500000,82.600000,82.416667,70.727273,85.083333
2020.0,40.454545,69.000000,81.909091,69.454545,93.000000
2021.0,42.000000,78.400000,81.272727,74.600000,90.454545
2022.0,45.727273,72.272727,83.090909,68.200000,85.090909
2023.0,46.181818,70.000000,82.222222,70.181818,88.000000
2024.0,38.272727,73.636364,84.181818,69.454545,84.818182

In [11]:
df1.groupby(df1.Club_Join_Date).std(numeric_only=True)

,Roll_no,math_score,Reading_score,Writing_score,Placement_score
Club_Join_Date,,,,,
2018.0,28.211010,4.675587,3.741657,5.674015,7.995534
2019.0,21.807005,48.143766,4.461111,4.268276,7.051220
2020.0,16.452134,6.587868,4.887833,7.501515,7.648529
2021.0,24.494897,27.015222,5.274294,5.358275,8.238491
2022.0,21.698345,4.839234,5.375026,5.493430,8.312094
2023.0,21.409429,7.071068,4.206476,5.653639,8.402381
2024.0,29.110448,5.315500,5.115040,6.713623,6.823755

In [12]:
df1.groupby(df1.Club_Join_Date).describe()

               Roll_no                                                       \
                 count       mean        std   min    25%   50%   75%   max
Club_Join_Date
2018.0             9.0  41.111111  28.211010   6.0  11.00  54.0  64.0  79.0
2019.0            12.0  28.500000  21.807005   2.0  11.25  25.0  36.5  68.0
2020.0            11.0  40.454545  16.452134  14.0  32.50  38.0  45.0  73.0
2021.0            11.0  42.000000  24.494897   3.0  23.00  47.0  60.5  72.0
2022.0            11.0  45.727273  21.698345  16.0  27.50  52.0  62.0  80.0
2023.0            11.0  46.181818  21.409429  13.0  33.50  44.0  64.0  75.0
2024.0            11.0  38.272727  29.110448   1.0  12.00  41.0  63.0  78.0

               math_score             ... Writing_score       Placement_score  \
                    count       mean  ...           75%   max           count
Club_Join_Date                        ...
2018.0                9.0  70.888889  ...         76.00  80.0             8.0
2019.0               10.0  82.600000  ...         73.50  79.0            12.0
2020.0               11.0  69.000000  ...         76.50  80.0             9.0
2021.0               10.0  78.400000  ...         77.75  80.0            11.0
2022.0               11.0  72.272727  ...         70.75  78.0            11.0
2023.0               11.0  70.000000  ...         74.00  78.0            11.0
2024.0               11.0  73.636364  ...         74.00  80.0            11.0


                     mean       std   min    25%   50%    75%    max
Club_Join_Date
2018.0          88.750000  7.995534  78.0  83.25  88.5  93.00  100.0
2019.0          85.083333  7.051220  75.0  81.25  83.5  89.25   97.0
2020.0          93.000000  7.648529  83.0  86.00  94.0  97.00  105.0
2021.0          90.454545  8.238491  78.0  84.00  95.0  96.50  100.0
2022.0          85.090909  8.312094  75.0  78.00  85.0  91.50   99.0
2023.0          88.000000  8.402381  77.0  80.00  90.0  94.50   99.0
2024.0          84.818182  6.823755  76.0  80.00  84.0  87.50   98.0

[7 rows x 40 columns]

In [13]:
df.groupby(df.Species).count()

                 Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
Species
Iris-setosa      50             50            50             50            50
Iris-versicolor  50             50            50             50            50
Iris-virginica   50             50            50             50            50

In [14]:
df.groupby(df.Species).count()

                 Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
Species
Iris-setosa      50             50            50             50            50
Iris-versicolor  50             50            50             50            50
Iris-virginica   50             50            50             50            50

In [16]:
df.groupby(df.Species).max()

                  Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
Species
Iris-setosa       50            5.8           4.4            1.9           0.6
Iris-versicolor  100            7.0           3.4            5.1           1.8
Iris-virginica   150            7.9           3.8            6.9           2.5

In [17]:
df.groupby(df.Species).mean()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm
Species,,,,,
Iris-setosa,25.5,5.006,3.418,1.464,0.244
Iris-versicolor,75.5,5.936,2.770,4.260,1.326
Iris-virginica,125.5,6.588,2.974,5.552,2.026

In [18]:
df.groupby(df.Species).std()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm
Species,,,,,
Iris-setosa,14.57738,0.352490,0.381024,0.173511,0.107210
Iris-versicolor,14.57738,0.516171,0.313798,0.469911,0.197753
Iris-virginica,14.57738,0.635880,0.322497,0.551895,0.274650